apiVersion: v1
kind: Service
metadata:
  name: fxgateway
  namespace: default
  labels:
    app: fxgateway
spec:
  selector:
    app: fxgateway
  type: LoadBalancer
  ports:
  - name: web
    port: 8080
