version: '2'
services:
    fxpriceservice-app:
        scale: 1
    fxpriceservice-mysql:
        scale: 1
    
    fxgateway-app:
        scale: 1
    fxgateway-mysql:
        scale: 1
    

    jhipster-registry:
        scale: 1


    jhipster-elasticsearch:
        scale: 1
    jhipster-logstash:
        scale: 1
    jhipster-console:
        scale: 1
    # Uncomment this section to enable Zipkin
    #jhipster-zipkin:
    #    scale: 1
