#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        dir('gateway') {
            sh "chmod +x mvnw"
            sh "./mvnw clean"
        }
    }

    stage('install tools') {
        dir('gateway') {
            sh "./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-yarn -DnodeVersion=v8.9.1 -DyarnVersion=v1.3.2"
        }
    }

    stage('yarn install') {
        dir('gateway') {
            sh "./mvnw com.github.eirslett:frontend-maven-plugin:yarn"
        }
    }

    stage('backend tests') {
        try {
            dir('gateway') {
                sh "./mvnw test"
            }
        } catch(err) {
            throw err
        } finally {
            junit '**/target/surefire-reports/TEST-*.xml'
        }
    }

    stage('frontend tests') {
        try {
            dir('gateway') {
                sh "./mvnw com.github.eirslett:frontend-maven-plugin:yarn -Dfrontend.yarn.arguments=test"
            }
        } catch(err) {
            throw err
        } finally {
            junit '**/target/test-results/karma/TESTS-*.xml'
        }
    }

    stage('package and deploy') {
        dir('gateway') {
            sh "./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy -DskipTests -Pprod -Dheroku.appName=fx-gateway"
        }
//        archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
    }

}
