#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
        sh "whoami"
    }

    stage('clean') {
        dir('fx-price-service') {
            sh "chmod +x mvnw"
            sh "./mvnw clean"
        }
    }


    stage('packaging') {
        dir('fx-price-service') {
            sh "./mvnw package -Pprod -DskipTests docker:build"
        }
    }

    stage('publish docker') {
        dir('fx-price-service') {
            sh "docker push pkcool/fxpriceservice"
        }
    }

}
