#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
        sh "whoami"
    }

    stage('clean') {
        dir('fx-price-service') {
            sh "chmod +x mvnw"
            sh "./mvnw clean"
        }
    }


    stage('packaging') {
        dir('fx-price-service') {
            sh "./mvnw package -Pprod -DskipTests docker:build"
            sh "docker image tag fxpriceservice pkcool/fxpriceservice"
        }
    }

    stage('publish docker') {
        dir('fx-price-service') {
            sh "docker push pkcool/fxpriceservice"
        }
    }

    stage('kube deployment') {
        dir('kubernetes') {
            sh "gcloud container clusters create fxts-kube  --machine-type=n1-standard-4 --num-nodes 1 --scopes cloud-platform --zone us-east1-b"
            sh "kubectl apply -f registry"
            sh "kubectl apply -f fxpriceservice"
            sh "kubectl apply -f fxgateway"
        }
    }

}
